### PR TITLE
Add test server and integration test for conditional requests

### LINKED ISSUE #196: Add more conditional request tests
Follow-up from #79 and #188 to add some additional test coverage.

### PR DESCRIPTION
**Pull request by netomi**
This fixes #196 .

This adds a docker image with the simple test server as outlined by you.
Added also a test for conditional request where the ETag expired which worked as expected.

Need to update the build workflow, I thought the docker-compose file will be taken into account.

### CODE REVIEW

**Comment by netomi** [comment]
hmm the same Dockerfile works when used with docker-compose, not sure what is going wrong in case of an action.

**Comment by netomi** [comment]
hmm closing the PR to avoid more actions from being run.
Can you cancel this one: https://github.com/requests-cache/aiohttp-client-cache/actions/runs/6677082725 ?

Using a custom action with docker is behaving unexpected, will look for other options.

**Comment by JWCook** [comment]
I can set this up if you'd like. It might be easier to skip Docker and run the app in the same virtualenv as the tests ([WIP example here](https://github.com/requests-cache/aiohttp-client-cache/compare/main...test-app)).

**Comment by netomi** [comment]
It looks like when you use docker in a GitHub action it behaves differently to a published docker image. I have seen some examples how to just add scripts to your workflow to run a gunicorn daemon, will try this out in my fork, and when its working will re-open the PR. If I fail I will come back to you.

**Pull request closed without merging**
