### PR TITLE
Add asyncio.Lock mutex to _request

### PR DESCRIPTION
**Pull request by rudcode**
With this change if there is simultaneous request to the same url at the same time, it will only fetch the url once and the rest is feeded from cache

Open for any feedback

### CODE REVIEW

**Comment by olk-m** [comment]
@rudcode Thank you for a PR. Could you please rebase and resolve merge conflicts?

I think that that the code works and I have no remarks, but it would be nice to add a test because a non-working locking will not fail CI. Something like:

```py
# 1. You need to mock `Backend.write()`.

# 2. Then call the same URL concurrently.
await asyncio.gather(*[session.get('http://localhost:8080/') for _ in range(10)])

# 3. Assert that `write()` was called only once.
mocked.bachend_write.assert_called_once()
```

**Comment by rudcode** [comment]
Hi @olk-m, okay, I'll rebase and try to add the test for this change. Thank you for the feedback, really appreciate it.

**Comment by JWCook** [comment]
Looks like this auto-closed because your fork's main is now the same as this repo's main, but feel free to reopen this or create a new PR.

I'm fine with adding a lock for identical requests, as long as it doesn't impact concurrent performance and there are tests added for the new behavior.

**Comment by JWCook** [comment]
@olk-m Is this basically the same approach you were planning to take for [#903](https://github.com/orgs/requests-cache/discussions/903)?

**Comment by olk-m** [comment]
> @olk-m Is this basically the same approach you were planning to take for [#903](https://github.com/orgs/requests-cache/discussions/903)?

Yes, although I did not have an implementation idea, this functionality is something I was thinking of adding in the future.

**Pull request closed without merging**
