### PR TITLE
Support for conditional requests

### LINKED ISSUE #79: Add support for conditional requests with ETag and Last-Modified headers
Quick summary of how this would work:
* If a cached response contains an `ETag` header, add an `If-None-Match` header to the new request
* If a cached response contains a `Last-Modified` header, add an `If-Modified-Since` header to the new request
* If a `304 Not Modified` response is received, return the cached response and update expiration and headers (if changed)
* If a `200` response is received, update the cache and return the new response

### PR DESCRIPTION
**Pull request by netomi**
This PR adds support for conditional requests.

I extracted the relevant code in a separate method so that I can check in a test whether it was called with mocking.
However, it would be great if httpbin would support an endpoint to changes its etag over time. Will look into that and provide a patch there so we can use it here as well if accepted.

This fixes #79 .

Code cov needs to be improved though.

### CODE REVIEW

**Comment by JWCook** [comment]
Thank you for putting this together. I appreciate it!

**Comment by netomi** [comment]
I still work on improving code coverage in the test, need a proper endpoint I can use during the tests. httpbin does not support that and is basically a dead project. It probably makes sense to create a fork supporting something like that.

I have a pretty good idea how this could be done, e.g. a /cache/10 endpoint  that updates the etag every 10s.

The etag would be generated from the current time in an interval based on the parameter.

There is a function available that can do that: https://gist.github.com/mscheper/9c39091e12f2ca8addb3d5eef7a40480

**Comment by JWCook** [comment]
@netomi I believe I handled this in requests-cache with mock responses instead of real requests + httpbin. I used the `requests-mock` library there, and [aioresponses](https://github.com/pnuckowski/aioresponses) is a similar one available for aiohttp.

If you want to test with a real endpoint, I think it would be simpler to make a separate test app rather than forking httpbin. Here's an example with Flask that does what you describe:

```py
from datetime import datetime
from hashlib import md5
from flask import Flask, request

app = Flask(__name__)


@app.route("/cache/<int:interval>")
def cache(interval):
    """Cacheable endpoint that uses an ETag that resets every `interval` seconds"""
    now = datetime.now()
    server_etag = md5(str(now.second // interval).encode()).hexdigest()
    request_etag = request.headers.get("If-None-Match")
    if request_etag == server_etag:
        return ("NOT MODIFIED", 304)
    else:
        return ("OK", 200, {"ETag": server_etag})
```

**Comment by netomi** [comment]
that is really nice will work on a PR

**Comment by JWCook** [comment]
These changes are now available in v0.10. Thank you again for your help!

Just fyi, at some point in the future I may merge some of this logic into the `CacheActions` class (similar to the current layout in requests-cache, to separate general HTTP cache logic from the aiohttp-specific parts).

**Comment by netomi** [comment]
great, so I can update my app to use that version and remove my workaround. Putting the logic into the CacheActions class certainly makes sense! 

btw. could you also make a release from the 0.10.0 tag? The latest release is still 0.9.

**Comment by JWCook** [comment]
Yes, I'll add that shortly.

**Pull request merged**
